query getAllAttendance($date: LocalDate, $search: String) {
  attendances(
    where: {
      currentDate: { eq: $date }
      or: [
        { user: { employeeName: { contains: $search } } }
        { user: { staffId: { contains: $search } } }
      ]
    }
  ) {
    clockIn
    clockOut
    currentDate
    totalHoursWorked
    user {
      id
      staffId
      employeeName
    }
  }
}

# query getAllAttendance {
#   attendances {
#     clockIn
#     clockOut
#     currentDate
#     totalHoursWorked
#     user {
#       id
#       staffId
#       employeeName
#     }
#   }
# }

query getAttendanceByDate(
  $startDate: LocalDate
  $endDate: LocalDate
  $search: String
) {
  attendances(
    where: {
      and: [{ currentDate: { gte: $startDate, lte: $endDate } }]
      or: [
        { user: { employeeName: { contains: $search } } }
        { user: { staffId: { contains: $search } } }
      ]
    }
  ) {
    id
    clockIn
    clockOut
    clockingType
    totalHoursWorked
    user {
      staffId
      employeeName
      email
    }
  }
}
