query TotalStats($startDay: LocalDate!, $stopDate: LocalDate!) {
  dashboardTotalStats(startDate: $startDay, endDate: $stopDate) {
    totalEmployees
    employeesClockedIn
    employeesClockedOut
    totalAbsent
    totalLeaves
  }
}

query ClockTime($startDay: LocalDate!, $stopDate: LocalDate!) {
  averageClockTime(startDate: $startDay, endDate: $stopDate) {
    averageClockIn
    averageClockOut
  }
}

query attendanceGraphData($startDay: LocalDate!, $stopDate: LocalDate!) {
  graphData(startDate: $startDay, endDate: $stopDate) {
    day
    clockedInCount
    absent
    onLeave
  }
}

query MostPunctual($startDay: LocalDate!, $stopDate: LocalDate!) {
  punctualEmployees(startday: $startDay, stopdate: $stopDate) {
    employeeName
    timeOfDay
  }
}

query LateEmployees($startDay: LocalDate!, $stopDate: LocalDate!) {
  lateEmployees(startday: $startDay, stopdate: $stopDate) {
    employeeName
    timeOfDay
  }
}

query MostUnproductive($startDay: LocalDate!, $stopDate: LocalDate!) {
  mostWastedHours(startday: $startDay, stopdate: $stopDate) {
    employeeName
    totalWastedHours
  }
}
query DashboardRequests($startDay: LocalDate!, $stopDate: LocalDate!) {
  requestLogs(startday: $startDay, stopdate: $stopDate) {
    employeeName
    timeOfDay
  }
}

query WorkHourSummary($startDay: LocalDate!, $stopDate: LocalDate!) {
  workHoursSummary(startday: $startDay, stopdate: $stopDate) {
    totalWorkingHours
    totalOffHours
  }
}
